openapi: 3.0.3
info:
  title: API Atendimento
  description: |-
    Api de gerenciamento de triagem online para o SUS - FIAP fase 5 Tech Challenge
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost:8080
    description: Local server

tags:
  - name: Atendimento
    description: Todo sobre atendimento
  - name: Historico
    description: Todo sobre historico do paciente
  - name: Avaliacao
    description: Todo sobre avaliações de atendimentos

paths:
  /atendimento/login:
    post:
      tags:
        - Atendimento
      summary: Realiza o login
      description: Dado as credenciais de um usuario, retorna o token de acesso
      operationId: realizaLogin
      requestBody:
        description: Credenciais do usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Não autorizado
  /atendimento/iniciar:
    get:
      tags:
        - Atendimento
      summary: Inicia o atendimento
      description: Inicia o processo de atendimento
      operationId: iniciarAtendimento
      parameters:
        - name: pagina
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            default: 0
            example: 1
        - name: porPagina
          in: query
          description: Número de itens por página
          required: false
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnidadePaginadaResponse'
        '401':
          description: Não autorizado
  /atendimento/enfermidade:
    get:
      tags:
        - Atendimento
      summary: Consulta enfermidades
      description: Consulta os tipos de enfermidades
      operationId: consultarEnfermidade
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EnfermidadeResponse'
        '401':
          description: Não autorizado
  /atendimento/registrar:
    post:
      tags:
        - Atendimento
      summary: Registra enfermidade do paciente
      description: Registra a enfermidade do paciente para dar inicio ao processo de triagem
      operationId: registrarEnfermidade
      requestBody:
        description: Credenciais do usuario
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrarEnfermidadeRequest'
        required: true
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrarEnfermidadeResponse'
        '401':
          description: Não autorizado
  /atendimento/confirmar/chegada:
    get:
      tags:
        - Atendimento
      summary: Confirmar chegada na unidade
      description: confirma qeu chegou na unidade e vai ser atendido pelo médico
      operationId: confirmarChegada
      parameters:
        - name: idAtendimento
          in: query
          description: ID do atendimento
          required: true
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
          schema:
            type: string
      responses:
        '202':
          description: confirmação de chegada
        '401':
          description: Não autorizado
  /atendimento/finalizar:
    post:
      tags:
        - Atendimento
      summary: Finaliza o atendimento
      description: finaliza o atendimento do paciente finalizando sua ficha e gerando o historico
      operationId: finalizarAtendimento
      requestBody:
        description: Credenciais do medido e do atendimento
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinalizarAtendimentoRequest'
      responses:
        '202':
          description: finalizado
        '401':
          description: Não autorizado
  /atendimento/avalicao:
    get:
      tags:
        - Avaliacao
      summary: Realiza consulta de avaliação
      description: Retorna as avaliações de atendimento por medico ou unidade
      operationId: consultarAvaliacoes
      parameters:
        - name: pagina
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            default: 0
            example: 1
        - name: porPagina
          in: query
          description: Número de itens por página
          required: false
          schema:
            type: integer
            default: 10
            example: 10
        - name: idUnidade
          in: query
          description: ID da unidade
          required: false
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
          schema:
            type: string
        - name: idMedico
          in: query
          description: ID do médico
          required: false
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
          schema:
            type: string
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvaliacaoPaginadaResponse'
        '400':
          description: Requisição mal sucedida
        '401':
          description: Não autorizado
      x-codegen-request-validator:
        oneOf:
          - required:
              - idUnidade
          - required:
              - idMedico
    post:
      tags:
        - Avaliacao
      summary: Avaliar o atendimento
      description: Paciente realiza a avaliação do atendimento
      operationId: avaliarAtendimento
      requestBody:
        description: Dados da avaliação
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AvaliacaoRequest'
      responses:
        '202':
          description: finalizado
        '401':
          description: Não autorizado

  /atendimento/historico:
    get:
      tags:
        - Historico
      summary: Realiza consulta do historico
      description: Retorna o historico do paciente ou histórico de atendimento do médico
      operationId: consultarHistorico
      parameters:
        - name: pagina
          in: query
          description: Número da página
          required: false
          schema:
            type: integer
            default: 0
            example: 1
        - name: porPagina
          in: query
          description: Número de itens por página
          required: false
          schema:
            type: integer
            default: 10
            example: 10
        - name: idPaciente
          in: query
          description: ID do paciente
          required: false
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
          schema:
            type: string
        - name: idMedico
          in: query
          description: ID do médico
          required: false
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
          schema:
            type: string
      responses:
        '200':
          description: Operação bem-sucedida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricoPaginadaResponse'
        '400':
          description: Requisição mal sucedida
        '401':
          description: Não autorizado
      x-codegen-request-validator:
        oneOf:
          - required:
              - idPaciente
          - required:
              - idMedico

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          description: email do usuário
          example: usuario@email.com
        senha:
          type: string
          description: senha do usuário
          example: senha123
    TokenResponse:
      type: object
      properties:
        token:
          type: string
          description: token do usuário
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
    UnidadeResponse:
      type: object
      properties:
        id:
          type: string
          description: id da unidade
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        nome:
          type: string
          description: nome da unidade
          example: Postinho
        endereco:
          type: string
          description: endereco da unidade
          example: Praça da Sé, 123
        quantidadeMedicos:
          type: integer
          description: quantidade de medicos atendendo na unidade
          example: 2
        quantidadePacientes:
          type: integer
          description: quantidade de pacientes na fila
          example: 5
        tempoMedioAtendimento:
          type: string
          description: tempo medio de atendimento por paciente
          example: Aproximadamente 12 minutos
        especialidades:
          type: array
          items:
            $ref: "#/components/schemas/EspecialidadesResponse"
    EspecialidadesResponse:
        type: object
        properties:
          nome:
            type: string
            description: nome da especialidade
            example: Clinica Geral
          descricao:
            type: string
            description: descricao da especialidade
            example: Oferecemos atendimento médico completo e personalizado
    Enfermidade:
      type: object
      properties:
        id:
          type: string
          description: id da enfermidade
          example: RESFRIADO
        comentario:
          type: string
          description: comentario sobre a enfermidade
          example: Resfriado a 3 dias
    EnfermidadeResponse:
      type: object
      properties:
        id:
          type: string
          description: id da enfermidade
          example: RESFRIADO
    UnidadePaginadaResponse:
      type: object
      properties:
        pagina:
          type: integer
          example: 1
        porPagina:
          type: integer
          example: 10
        total:
          type: integer
          format: int64
          example: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/UnidadeResponse"
    AvaliacaoPaginadaResponse:
      type: object
      properties:
        pagina:
          type: integer
          example: 1
        porPagina:
          type: integer
          example: 10
        total:
          type: integer
          format: int64
          example: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/AvaliacaoResponse"
    RegistrarEnfermidadeRequest:
      type: object
      properties:
        idUnidade:
          type: string
          description: id da unidade
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        idPaciente:
          type: string
          description: id do paciente
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        enfermidades:
          type: array
          items:
            $ref: "#/components/schemas/Enfermidade"
    RegistrarEnfermidadeResponse:
      type: object
      properties:
        id:
          type: string
          description: id do atendimento
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        numero:
          type: integer
          description: seu numero na fila de atendimento
          example: 99
    FinalizarAtendimentoRequest:
      type: object
      properties:
        idAtendimento:
          type: string
          description: id do atendimento
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        idMedico:
          type: string
          description: id do medico
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        comentario:
          type: string
          description: comentario sobre atendimento
          example: receitei que fique em casa e tome um antigripal
    AvaliacaoRequest:
      type: object
      properties:
        idAtendimento:
          type: string
          description: id do atendimento
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        nota:
          type: integer
          description: nota do atendimento
          example: 2
          minimum: 1
          maximum: 5
        comentario:
          type: string
          description: comentario sobre avaliação
          example: medico muito ruim não me deu atenção
    AvaliacaoResponse:
      type: object
      properties:
        idUnidade:
          type: string
          description: id da unidade
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        idMedico:
          type: string
          description: id do Médico
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        nota:
          type: integer
          description: nota do atendimento
          example: 2
          minimum: 1
          maximum: 5
        comentario:
          type: string
          description: comentario sobre avaliação
          example: medico muito ruim não me deu atenção
    HistoricoResponse:
      type: object
      properties:
        id:
          type: string
          description: id do historico
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        idPaciente:
          type: string
          description: id do paciente
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        idMedico:
          type: string
          description: id do medico
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        idUnidade:
          type: string
          description: id da unidade
          example: 2e84348b-953f-4d3c-a0ef-3e5e31a693cb
        dataHoraInicio:
          type: string
          format: date-time
          description: data e hora de inicio do atendimento
          example: 2023-10-01T10:00:00Z
        dataHoraFim:
          type: string
          format: date-time
          description: data e hora de fim do atendimento
          example: 2023-10-01T11:00:00Z
        status:
          type: string
          description: status do atendimento
          example: FINALIZADO
        enfermidade:
          type: array
          items:
            $ref: "#/components/schemas/Enfermidade"
        comentario:
          type: string
          description: comentario sobre atendimento
          example: receitei que fique em casa e tome um antigripal
    HistoricoPaginadaResponse:
      type: object
      properties:
        pagina:
          type: integer
          example: 1
        porPagina:
          type: integer
          example: 10
        total:
          type: integer
          format: int64
          example: 100
        items:
          type: array
          items:
            $ref: "#/components/schemas/HistoricoResponse"