openapi: 3.0.3
info:
  title: API Atendimento
  description: |-
    Api de gerenciamento de triagem online para o SUS - FIAP fase 5 Tech Challenge
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://localhost:8080
    description: Local server

tags:
  - name: Atendimento
    description: all about Products

paths:
  /hola:
    get:
      tags:
        - Atendimento
      summary: Diz ola
      description: Retorna ola
      operationId: hola
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                example: ola
